# vim:ft=ruby et ts=2 sw=2:

#gem 'corvid'
gem "corvid", git: 'git://github.com/japgolly/corvid.git' # TODO Use proper Corvid once released

gem 'rake', group: :rake

group :test do
  gem 'ci_reporter', require: false
  gem 'simplecov', '>= 0.6.4', require: false
  gem 'guard', '>= 1.3.2', require: false
end if Dir.exists?('test')

group :test_unit do
  gem 'minitest'
  gem 'guard-minitest', '>= 0.5.0', require: false
  gem 'turn', '>= 0.9.4'
end if Dir.exists?('test/unit')

group :test_spec do
  gem 'rspec'
  gem 'guard-rspec', require: false
end if Dir.exists?('test/spec')

group :doc do
#  gem 'yard'
  gem 'yard', git: 'git://github.com/japgolly/yard.git', branch: 'happy_days' # TODO Use proper yard
end
